#! /usr/local/bin/perl

use strict;
use Cwd;
use File::Spec;

BEGIN {
  $^W = 1;  # Use warnings
  my $curdir = File::Spec->canonpath( Cwd::cwd() );
  unless ($curdir eq '/home/jason/Data-Form-Elements/Data-Form-Elements-0.5') {
    die ('This script must be run from /home/jason/Data-Form-Elements/Data-Form-Elements-0.5, not '."$curdir\n".
	 "Please re-run the Build.PL script here.\n");
  }
  @INC = 
    (
     '/opt/promoseal_lib',
     '/usr/local/lib/perl5/5.8.2/i686-linux-thread-multi',
     '/usr/local/lib/perl5/5.8.2/i686-linux-thread-multi',
     '/usr/local/lib/perl5/5.8.2',
     '/usr/local/lib/perl5/site_perl/5.8.2/i686-linux-thread-multi',
     '/usr/local/lib/perl5/site_perl/5.8.2/i686-linux-thread-multi',
     '/usr/local/lib/perl5/site_perl/5.8.2',
     '/usr/local/lib/perl5/site_perl/5.8.2/i686-linux-thread-multi',
     '/usr/local/lib/perl5/site_perl/5.8.2',
     '/usr/local/lib/perl5/site_perl',
     '/home/jason/Data-Form-Elements',
     '/usr/local/lib/perl5/5.8.2/i686-linux-thread-multi',
     '/usr/local/lib/perl5/5.8.2',
     '/usr/local/lib/perl5/site_perl/5.8.2/i686-linux-thread-multi',
     '/usr/local/lib/perl5/site_perl/5.8.2',
     '/usr/local/lib/perl5/site_perl',
     '/home/jason/Data-Form-Elements/Data-Form-Elements-0.5'
    );
}

use Module::Build;

if (-e 'Build.PL' and not Module::Build->up_to_date("Build.PL", $0)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.\n";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = Module::Build->resume (
  properties => {
    config_dir => '/home/jason/Data-Form-Elements/Data-Form-Elements-0.5/_build',
  },
);

$build->dispatch;
